/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    public VentanaPrincipal() {
        initComponents();

        tIDCustomer.setEditable(false);
        tIDOrder.setEditable(false);
        tIDShipment.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlShipments = new javax.swing.JTabbedPane();
        pCustomers = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tIDCustomer = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        bInsertar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        RegistrosCustomer = new javax.swing.JTable();
        pOrders = new javax.swing.JPanel();
        lIDOrder = new javax.swing.JLabel();
        tIDOrder = new javax.swing.JTextField();
        lIDCustomer = new javax.swing.JLabel();
        lFechaPedido = new javax.swing.JLabel();
        tIDCustomer2 = new javax.swing.JTextField();
        tFechaPedido = new javax.swing.JTextField();
        bInsertar1 = new javax.swing.JButton();
        bActualizar1 = new javax.swing.JButton();
        bEliminar1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        RegistrosOrder = new javax.swing.JTable();
        pShipments = new javax.swing.JPanel();
        bInsertar2 = new javax.swing.JButton();
        bActualizar2 = new javax.swing.JButton();
        bEliminar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tIDShipment = new javax.swing.JTextField();
        tIDOrders2 = new javax.swing.JTextField();
        tFechaEnvio = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        RegistrosShipment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("CRUD");

        jLabel2.setText("ID Customer:");

        lNombre.setText("Nombre:");

        bInsertar.setText("Insertar");

        bActualizar.setText("Actualizar");

        bEliminar.setText("Eliminar");

        RegistrosCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(RegistrosCustomer);
        if (RegistrosCustomer.getColumnModel().getColumnCount() > 0) {
            RegistrosCustomer.getColumnModel().getColumn(0).setResizable(false);
            RegistrosCustomer.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout pCustomersLayout = new javax.swing.GroupLayout(pCustomers);
        pCustomers.setLayout(pCustomersLayout);
        pCustomersLayout.setHorizontalGroup(
            pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomersLayout.createSequentialGroup()
                .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCustomersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(pCustomersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tIDCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185)
                        .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bActualizar)
                            .addGroup(pCustomersLayout.createSequentialGroup()
                                .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pCustomersLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(bInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(bEliminar))
                                .addGap(12, 12, 12)))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        pCustomersLayout.setVerticalGroup(
            pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCustomersLayout.createSequentialGroup()
                .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCustomersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(tIDCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNombre)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCustomersLayout.createSequentialGroup()
                        .addComponent(bInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bActualizar)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        pnlShipments.addTab("Customers", pCustomers);

        lIDOrder.setText("ID Order:");

        lIDCustomer.setText("ID Customer:");

        lFechaPedido.setText("Fecha pedido:");

        bInsertar1.setText("Insertar");

        bActualizar1.setText("Actualizar");

        bEliminar1.setText("Eliminar");

        RegistrosOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Order", "ID Customer", "Fecha pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(RegistrosOrder);
        if (RegistrosOrder.getColumnModel().getColumnCount() > 0) {
            RegistrosOrder.getColumnModel().getColumn(0).setResizable(false);
            RegistrosOrder.getColumnModel().getColumn(1).setResizable(false);
            RegistrosOrder.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pOrdersLayout = new javax.swing.GroupLayout(pOrders);
        pOrders.setLayout(pOrdersLayout);
        pOrdersLayout.setHorizontalGroup(
            pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOrdersLayout.createSequentialGroup()
                .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOrdersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6))
                    .addGroup(pOrdersLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pOrdersLayout.createSequentialGroup()
                                .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pOrdersLayout.createSequentialGroup()
                                        .addComponent(lIDOrder)
                                        .addGap(69, 69, 69)
                                        .addComponent(tIDOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pOrdersLayout.createSequentialGroup()
                                        .addComponent(lIDCustomer)
                                        .addGap(42, 42, 42)
                                        .addComponent(tIDCustomer2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(365, 365, 365))
                            .addGroup(pOrdersLayout.createSequentialGroup()
                                .addComponent(lFechaPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(283, 283, 283)))
                        .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pOrdersLayout.createSequentialGroup()
                                .addComponent(bInsertar1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOrdersLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pOrdersLayout.createSequentialGroup()
                                        .addComponent(bEliminar1)
                                        .addGap(12, 12, 12))
                                    .addComponent(bActualizar1))))))
                .addContainerGap())
        );
        pOrdersLayout.setVerticalGroup(
            pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOrdersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lIDOrder)
                            .addComponent(tIDOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lFechaPedido)))
                    .addGroup(pOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lIDCustomer)
                        .addComponent(tIDCustomer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pOrdersLayout.createSequentialGroup()
                        .addComponent(bInsertar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bActualizar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pnlShipments.addTab("Orders", pOrders);

        bInsertar2.setText("Insertar");

        bActualizar2.setText("Actualizar");

        bEliminar2.setText("Eliminar");

        jLabel3.setText("ID Shipment:");

        jLabel4.setText("ID Orders:");

        jLabel5.setText("Fecha envío:");

        RegistrosShipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Shipment", "ID Order", "Fecha envío"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(RegistrosShipment);
        if (RegistrosShipment.getColumnModel().getColumnCount() > 0) {
            RegistrosShipment.getColumnModel().getColumn(0).setResizable(false);
            RegistrosShipment.getColumnModel().getColumn(1).setResizable(false);
            RegistrosShipment.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pShipmentsLayout = new javax.swing.GroupLayout(pShipments);
        pShipments.setLayout(pShipmentsLayout);
        pShipmentsLayout.setHorizontalGroup(
            pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pShipmentsLayout.createSequentialGroup()
                .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pShipmentsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                    .addGroup(pShipmentsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pShipmentsLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(204, 204, 204))
                            .addGroup(pShipmentsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(40, 40, 40)
                                .addComponent(tFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pShipmentsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tIDOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tIDShipment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bInsertar2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bEliminar2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(bActualizar2))))
                .addContainerGap())
        );
        pShipmentsLayout.setVerticalGroup(
            pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pShipmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pShipmentsLayout.createSequentialGroup()
                        .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tIDOrders2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tIDShipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pShipmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pShipmentsLayout.createSequentialGroup()
                        .addComponent(bInsertar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bActualizar2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pnlShipments.addTab("Shipments", pShipments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlShipments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    public javax.swing.JTextField getTIDCustomer() {
        return tIDCustomer;
    }

    public javax.swing.JTextField getTNombre() {
        return tNombre;
    }

    public javax.swing.JTextField getTIDOrder() {
        return tIDOrder;
    }

    public javax.swing.JTextField getTIDCustomer2() {
        return tIDCustomer2;
    }

    public javax.swing.JTextField getTFechaPedido() {
        return tFechaPedido;
    }

    public javax.swing.JTextField getTIDShipment() {
        return tIDShipment;
    }

    public javax.swing.JTextField getTIDOrders2() {
        return tIDOrders2;
    }

    public javax.swing.JTextField getTFechaEnvio() {
        return tFechaEnvio;
    }

    public javax.swing.JButton getBInsertar() {
        return bInsertar;
    }

    public javax.swing.JButton getBActualizar() {
        return bActualizar;
    }

    public javax.swing.JButton getBEliminar() {
        return bEliminar;
    }

    public javax.swing.JButton getBInsertar1() {
        return bInsertar1;
    }

    public javax.swing.JButton getBActualizar1() {
        return bActualizar1;
    }

    public javax.swing.JButton getBEliminar1() {
        return bEliminar1;
    }

    public javax.swing.JButton getBInsertar2() {
        return bInsertar2;
    }

    public javax.swing.JButton getBActualizar2() {
        return bActualizar2;
    }

    public javax.swing.JButton getBEliminar2() {
        return bEliminar2;
    }

    public javax.swing.JTable getRegistrosCustomer() {
        return RegistrosCustomer;
    }

    public javax.swing.JTable getRegistrosOrder() {
        return RegistrosOrder;
    }

    public javax.swing.JTable getRegistrosShipment() {
        return RegistrosShipment;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RegistrosCustomer;
    private javax.swing.JTable RegistrosOrder;
    private javax.swing.JTable RegistrosShipment;
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bActualizar1;
    private javax.swing.JButton bActualizar2;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bEliminar1;
    private javax.swing.JButton bEliminar2;
    private javax.swing.JButton bInsertar;
    private javax.swing.JButton bInsertar1;
    private javax.swing.JButton bInsertar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lFechaPedido;
    private javax.swing.JLabel lIDCustomer;
    private javax.swing.JLabel lIDOrder;
    private javax.swing.JLabel lNombre;
    private javax.swing.JPanel pCustomers;
    private javax.swing.JPanel pOrders;
    private javax.swing.JPanel pShipments;
    private javax.swing.JTabbedPane pnlShipments;
    private javax.swing.JTextField tFechaEnvio;
    private javax.swing.JTextField tFechaPedido;
    private javax.swing.JTextField tIDCustomer;
    private javax.swing.JTextField tIDCustomer2;
    private javax.swing.JTextField tIDOrder;
    private javax.swing.JTextField tIDOrders2;
    private javax.swing.JTextField tIDShipment;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}
